Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,6 +35,11 @@ jobs:
         token='martcus:${{ secrets.ACTIONS_TOKEN }}'
         response=$(curl -u martcus:$token https://api.github.com/repos/martcus/devops-in-actions/actions/artifacts)
         id=$(echo $response | jq "[ .artifacts[] | select (.name == \"${{ steps.target-artifact.outputs.TARGET_ARTIFACT }}\" and .expired == false) | .id ] | max")
+        if [ -z "$id" ]; then
+          echo "Artifact ${{ steps.target-artifact.outputs.TARGET_ARTIFACT }} not found"
+          exit 1
+        fi
+        
         url=$(echo $response | jq "[ .artifacts[] | select (.id == $id) | .archive_download_url ]")
         echo "::set-output name=TARGET_URL::$(echo $url)"
         if [ -z "$url" ]; then
